# Generated by Django 6.0.3 on 2026-06-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowhold',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_holds_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowhold',
            name='worker_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_holds_as_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='escrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='escrow.escrowhold'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='escrowhold',
            index=models.Index(fields=['status'], name='escrow_hold_status_599674_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', '-created_at'], name='wallet_tran_user_id_1da2e3_idx'),
        ),
    ]
